(cl:defpackage segment_plans_objects-srv
  (:use )
  (:export
   "PLANTOPSEGMENTATION"
   "<PLANTOPSEGMENTATION-REQUEST>"
   "PLANTOPSEGMENTATION-REQUEST"
   "<PLANTOPSEGMENTATION-RESPONSE>"
   "PLANTOPSEGMENTATION-RESPONSE"
  ))

