(cl:defpackage reco_3d-srv
  (:use )
  (:export
   "ORIENTEDBOUNDINGBOXRECOGNITION"
   "<ORIENTEDBOUNDINGBOXRECOGNITION-REQUEST>"
   "ORIENTEDBOUNDINGBOXRECOGNITION-REQUEST"
   "<ORIENTEDBOUNDINGBOXRECOGNITION-RESPONSE>"
   "ORIENTEDBOUNDINGBOXRECOGNITION-RESPONSE"
   "ITERATIVECLOSESTPOINTRECOGNITION"
   "<ITERATIVECLOSESTPOINTRECOGNITION-REQUEST>"
   "ITERATIVECLOSESTPOINTRECOGNITION-REQUEST"
   "<ITERATIVECLOSESTPOINTRECOGNITION-RESPONSE>"
   "ITERATIVECLOSESTPOINTRECOGNITION-RESPONSE"
  ))

