/* Auto-generated by genmsg_cpp for file /home/gmanfred/devel/ros/packs/vision/reco/reco_texture/srv/TexturedRecognition.srv */
#ifndef RECO_TEXTURE_SERVICE_TEXTUREDRECOGNITION_H
#define RECO_TEXTURE_SERVICE_TEXTUREDRECOGNITION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "sensor_msgs/Image.h"
#include "std_msgs/String.h"


#include "std_msgs/String.h"

namespace reco_texture
{
template <class ContainerAllocator>
struct TexturedRecognitionRequest_ {
  typedef TexturedRecognitionRequest_<ContainerAllocator> Type;

  TexturedRecognitionRequest_()
  : cluster()
  , names()
  {
  }

  TexturedRecognitionRequest_(const ContainerAllocator& _alloc)
  : cluster(_alloc)
  , names(_alloc)
  {
  }

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _cluster_type;
   ::sensor_msgs::Image_<ContainerAllocator>  cluster;

  typedef std::vector< ::std_msgs::String_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::String_<ContainerAllocator> >::other >  _names_type;
  std::vector< ::std_msgs::String_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::String_<ContainerAllocator> >::other >  names;


  typedef boost::shared_ptr< ::reco_texture::TexturedRecognitionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reco_texture::TexturedRecognitionRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct TexturedRecognitionRequest
typedef  ::reco_texture::TexturedRecognitionRequest_<std::allocator<void> > TexturedRecognitionRequest;

typedef boost::shared_ptr< ::reco_texture::TexturedRecognitionRequest> TexturedRecognitionRequestPtr;
typedef boost::shared_ptr< ::reco_texture::TexturedRecognitionRequest const> TexturedRecognitionRequestConstPtr;


template <class ContainerAllocator>
struct TexturedRecognitionResponse_ {
  typedef TexturedRecognitionResponse_<ContainerAllocator> Type;

  TexturedRecognitionResponse_()
  : names()
  , result(0)
  {
  }

  TexturedRecognitionResponse_(const ContainerAllocator& _alloc)
  : names(_alloc)
  , result(0)
  {
  }

  typedef std::vector< ::std_msgs::String_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::String_<ContainerAllocator> >::other >  _names_type;
  std::vector< ::std_msgs::String_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::String_<ContainerAllocator> >::other >  names;

  typedef int32_t _result_type;
  int32_t result;

  enum { SUCCESS = 0 };
  enum { TF_ERROR = 1 };

  typedef boost::shared_ptr< ::reco_texture::TexturedRecognitionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reco_texture::TexturedRecognitionResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct TexturedRecognitionResponse
typedef  ::reco_texture::TexturedRecognitionResponse_<std::allocator<void> > TexturedRecognitionResponse;

typedef boost::shared_ptr< ::reco_texture::TexturedRecognitionResponse> TexturedRecognitionResponsePtr;
typedef boost::shared_ptr< ::reco_texture::TexturedRecognitionResponse const> TexturedRecognitionResponseConstPtr;

struct TexturedRecognition
{

typedef TexturedRecognitionRequest Request;
typedef TexturedRecognitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct TexturedRecognition
} // namespace reco_texture

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::reco_texture::TexturedRecognitionRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::reco_texture::TexturedRecognitionRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::reco_texture::TexturedRecognitionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0e36f02deaa3a2f1989a359c2bfe55c2";
  }

  static const char* value(const  ::reco_texture::TexturedRecognitionRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0e36f02deaa3a2f1ULL;
  static const uint64_t static_value2 = 0x989a359c2bfe55c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::reco_texture::TexturedRecognitionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "reco_texture/TexturedRecognitionRequest";
  }

  static const char* value(const  ::reco_texture::TexturedRecognitionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::reco_texture::TexturedRecognitionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sensor_msgs/Image cluster\n\
std_msgs/String[] names\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
";
  }

  static const char* value(const  ::reco_texture::TexturedRecognitionRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::reco_texture::TexturedRecognitionResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::reco_texture::TexturedRecognitionResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::reco_texture::TexturedRecognitionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7082f925546d831701ff355d8ede6b57";
  }

  static const char* value(const  ::reco_texture::TexturedRecognitionResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7082f925546d8317ULL;
  static const uint64_t static_value2 = 0x01ff355d8ede6b57ULL;
};

template<class ContainerAllocator>
struct DataType< ::reco_texture::TexturedRecognitionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "reco_texture/TexturedRecognitionResponse";
  }

  static const char* value(const  ::reco_texture::TexturedRecognitionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::reco_texture::TexturedRecognitionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
int32 SUCCESS=0\n\
int32 TF_ERROR=1\n\
\n\
\n\
std_msgs/String[] names\n\
\n\
\n\
int32 result\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
";
  }

  static const char* value(const  ::reco_texture::TexturedRecognitionResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::reco_texture::TexturedRecognitionRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.cluster);
    stream.next(m.names);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TexturedRecognitionRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::reco_texture::TexturedRecognitionResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.names);
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TexturedRecognitionResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<reco_texture::TexturedRecognition> {
  static const char* value() 
  {
    return "c23f34f647e21ac1337db3cd60ac9075";
  }

  static const char* value(const reco_texture::TexturedRecognition&) { return value(); } 
};

template<>
struct DataType<reco_texture::TexturedRecognition> {
  static const char* value() 
  {
    return "reco_texture/TexturedRecognition";
  }

  static const char* value(const reco_texture::TexturedRecognition&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<reco_texture::TexturedRecognitionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c23f34f647e21ac1337db3cd60ac9075";
  }

  static const char* value(const reco_texture::TexturedRecognitionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<reco_texture::TexturedRecognitionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "reco_texture/TexturedRecognition";
  }

  static const char* value(const reco_texture::TexturedRecognitionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<reco_texture::TexturedRecognitionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c23f34f647e21ac1337db3cd60ac9075";
  }

  static const char* value(const reco_texture::TexturedRecognitionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<reco_texture::TexturedRecognitionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "reco_texture/TexturedRecognition";
  }

  static const char* value(const reco_texture::TexturedRecognitionResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // RECO_TEXTURE_SERVICE_TEXTUREDRECOGNITION_H

