/* Auto-generated by genmsg_cpp for file /home/gmanfred/devel/ros/my_packs/frontEnd/msg/CloudArray.msg */
#ifndef FRONTEND_MESSAGE_CLOUDARRAY_H
#define FRONTEND_MESSAGE_CLOUDARRAY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "sensor_msgs/PointCloud2.h"

namespace frontEnd
{
template <class ContainerAllocator>
struct CloudArray_ {
  typedef CloudArray_<ContainerAllocator> Type;

  CloudArray_()
  : clouds()
  {
  }

  CloudArray_(const ContainerAllocator& _alloc)
  : clouds(_alloc)
  {
  }

  typedef std::vector< ::sensor_msgs::PointCloud2_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::other >  _clouds_type;
  std::vector< ::sensor_msgs::PointCloud2_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::other >  clouds;


  typedef boost::shared_ptr< ::frontEnd::CloudArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::frontEnd::CloudArray_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CloudArray
typedef  ::frontEnd::CloudArray_<std::allocator<void> > CloudArray;

typedef boost::shared_ptr< ::frontEnd::CloudArray> CloudArrayPtr;
typedef boost::shared_ptr< ::frontEnd::CloudArray const> CloudArrayConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::frontEnd::CloudArray_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::frontEnd::CloudArray_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace frontEnd

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::frontEnd::CloudArray_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::frontEnd::CloudArray_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::frontEnd::CloudArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a1ae9b373e3c6d99d77b25f8b07122a1";
  }

  static const char* value(const  ::frontEnd::CloudArray_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa1ae9b373e3c6d99ULL;
  static const uint64_t static_value2 = 0xd77b25f8b07122a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::frontEnd::CloudArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "frontEnd/CloudArray";
  }

  static const char* value(const  ::frontEnd::CloudArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::frontEnd::CloudArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sensor_msgs/PointCloud2[] clouds\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
\n\
";
  }

  static const char* value(const  ::frontEnd::CloudArray_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::frontEnd::CloudArray_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.clouds);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CloudArray_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::frontEnd::CloudArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::frontEnd::CloudArray_<ContainerAllocator> & v) 
  {
    s << indent << "clouds[]" << std::endl;
    for (size_t i = 0; i < v.clouds.size(); ++i)
    {
      s << indent << "  clouds[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "    ", v.clouds[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // FRONTEND_MESSAGE_CLOUDARRAY_H

